# Generated by Django 4.0.1 on 2022-01-19 10:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('breast', models.PositiveSmallIntegerField(verbose_name='Грудь')),
                ('growth', models.PositiveSmallIntegerField(verbose_name='Рост')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('price_30_home', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена 30 минут (апартаменты)')),
                ('price_1h_home', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена 1 час (апартаменты)')),
                ('price_2h_home', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена 2 час (апартаменты)')),
                ('price_night_home', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена ночь (апартаменты)')),
                ('price_1h_departure', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена 1 час (выезд)')),
                ('price_2h_departure', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена 2 час (выезд)')),
                ('price_night_departure', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена ночь (выезд)')),
                ('status', models.CharField(choices=[('draft', 'Приостановлена'), ('published', 'Опубликована')], default='draft', max_length=10, verbose_name='Статус')),
                ('verified', models.BooleanField(default=False, verbose_name='Реальное фото')),
                ('test_photo', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Проверочное фото')),
                ('can_search', models.BooleanField(default=False, verbose_name='Поиск по номеру')),
                ('parking', models.BooleanField(default=False, verbose_name='Парковка')),
                ('apartment', models.BooleanField(default=False, verbose_name='Отдельная квартира')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Опубликовано')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('whatsapp', models.CharField(blank=True, max_length=300, null=True, verbose_name='WhatsApp')),
                ('telegram', models.CharField(blank=True, max_length=300, null=True, verbose_name='Telegram')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('max_images', models.IntegerField(default=1, verbose_name='Максимальное количество картинок')),
                ('max_videos', models.IntegerField(default=0, verbose_name='Максимальное количество видео')),
                ('adds_left', models.IntegerField(default=0, verbose_name='Количество подбросов')),
                ('active_advertising', models.BooleanField(default=False, verbose_name='Активна реклама')),
                ('start_add_at', models.TimeField(blank=True, null=True, verbose_name='Показывать обьявления после')),
                ('timedelta_add', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Длительность показа обьявления в часах')),
                ('rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='girls', to='rates.rate', verbose_name='Тарифный план')),
            ],
            options={
                'verbose_name': 'Девушка',
                'verbose_name_plural': 'Девушки',
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Услуга')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('video', 'Видео'), ('profile', 'Профиль')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Просмотр',
                'verbose_name_plural': 'Просмотры',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/%Y/%m/%d', verbose_name='Видео')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='girls.girl', verbose_name='Девушка')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('body', models.TextField(max_length=400, verbose_name='Текст отзыва')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='girls.girl', verbose_name='Девушка')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Район')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='girls.city', verbose_name='город')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Фото')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='girls.girl', verbose_name='Девушка')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='girl',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='girls', to='girls.Service', verbose_name='Услуги'),
        ),
    ]
