# Generated by Django 4.0.1 on 2022-01-19 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='girl',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='girls', to='girls.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='girl',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='girls', to='girls.region', verbose_name='Район'),
        ),
    ]
