# Generated by Django 4.0.1 on 2022-01-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0002_girl_city_girl_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='girl',
            name='rate_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание тарифа'),
        ),
    ]
