# Generated by Django 4.0.1 on 2022-01-19 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0003_girl_rate_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='girls.girl', verbose_name='Девушка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='girl',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
