# Generated by Django 4.0.1 on 2022-01-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0004_view_profile_alter_girl_created_alter_girl_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('-name',), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('-name',), 'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
    ]
