# Generated by Django 4.0.1 on 2022-01-21 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('girls', '0006_girl_user_alter_girl_status_alter_review_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
