# Generated by Django 4.0.1 on 2022-01-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0008_alter_girl_age_alter_girl_breast_alter_girl_growth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='girl',
            name='can_delete_comments',
            field=models.BooleanField(default=False, verbose_name='Может удалять комментарии'),
        ),
    ]
