# Generated by Django 4.0.1 on 2022-01-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0009_girl_can_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='girl',
            name='timedelta_add',
        ),
        migrations.AddField(
            model_name='girl',
            name='end_add_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Окончание рекламы'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='start_add_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало рекламы'),
        ),
    ]
