# Generated by Django 4.0.1 on 2022-01-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0010_remove_girl_timedelta_add_girl_end_add_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='girl',
            name='arive',
            field=models.BooleanField(default=False, verbose_name='Выезд'),
        ),
    ]
