# Generated by Django 4.0.1 on 2022-01-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0011_girl_arive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='girl',
            old_name='arive',
            new_name='arrive',
        ),
    ]
