# Generated by Django 4.0.1 on 2022-02-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0013_girl_max_price_girl_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='girl',
            name='auto_activation_advertising_at',
            field=models.DateField(blank=True, null=True, verbose_name='Автоматическая активация рекламы после'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='active_advertising',
            field=models.BooleanField(default=True, verbose_name='Активна реклама'),
        ),
    ]
