# Generated by Django 4.0.1 on 2022-02-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0014_girl_auto_activation_advertising_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='girl',
            name='end_add_at',
        ),
        migrations.RemoveField(
            model_name='girl',
            name='start_add_at',
        ),
    ]
