# Generated by Django 4.0.1 on 2022-02-13 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0015_remove_girl_end_add_at_remove_girl_start_add_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=10, verbose_name='тип')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retentions', to='girls.girl', verbose_name='девушка')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
