# Generated by Django 4.0.1 on 2022-02-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0016_retention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retention',
            name='type',
            field=models.CharField(max_length=20, verbose_name='тип'),
        ),
    ]
