# Generated by Django 4.0.1 on 2022-02-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0017_alter_retention_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='girl',
            name='auto_activate_rate_at',
            field=models.DateField(blank=True, null=True, verbose_name='Автоматическая активация тарифного плана после'),
        ),
    ]
