# Generated by Django 4.0.1 on 2022-01-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.CharField(choices=[('inert', 'Не был'), ('good', 'Проходящий'), ('bad', 'Гемор')], max_length=10),
        ),
    ]
