# Generated by Django 4.0.1 on 2022-02-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_review_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.CharField(choices=[('inert', 'Was not'), ('good', 'Passing'), ('bad', 'Problem')], max_length=10),
        ),
    ]
