# Generated by Django 4.0.1 on 2022-01-19 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Toss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Автоподброс',
                'verbose_name_plural': 'Автоподбросы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тариф')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
                ('sub_name', models.CharField(max_length=100, verbose_name='Описание тарифа')),
                ('photos', models.SmallIntegerField(default=1, help_text='-1 для безлимита', verbose_name='Фото')),
                ('videos', models.SmallIntegerField(default=0, help_text='-1 для безлимита', verbose_name='Видео')),
                ('adds', models.SmallIntegerField(default=0, help_text='-1 для безлимита', verbose_name='Автоподбросы')),
                ('days', models.SmallIntegerField(help_text='-1 для безлимита', verbose_name='Количество дней')),
                ('days_bonus', models.PositiveSmallIntegerField(default=0, verbose_name='Бонусное количество дней')),
                ('photos_bonus', models.PositiveSmallIntegerField(default=0, verbose_name='Бонусное количество фото')),
                ('videos_bonus', models.PositiveSmallIntegerField(default=0, verbose_name='Бонусное количество видео')),
                ('adds_bonus', models.PositiveSmallIntegerField(default=0, verbose_name='Бонусное количество автоподбросов')),
                ('bonus_start', models.DateTimeField(blank=True, null=True)),
                ('bonus_end', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='rates.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ('-created',),
            },
        ),
    ]
