# Generated by Django 4.0.1 on 2022-01-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_alter_rate_bonus_end_alter_rate_bonus_start_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toss',
            options={'ordering': ('quantity',), 'verbose_name': 'Автоподброс', 'verbose_name_plural': 'Автоподбросы'},
        ),
    ]
