# Generated by Django 4.0.1 on 2022-02-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='adds_bonus',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='bonus_end',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='bonus_start',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='days_bonus',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='photos_bonus',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='videos_bonus',
        ),
        migrations.AddField(
            model_name='rate',
            name='type',
            field=models.TextField(blank=True, choices=[('start', 'Стартовый'), ('lux', 'Люксовый')], default='', null=True, verbose_name='Тип тарифа'),
        ),
    ]
