# Generated by Django 4.0.1 on 2022-01-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Элемент покупки', 'verbose_name_plural': 'Элементы покупки'},
        ),
    ]
