# Generated by Django 4.0.1 on 2022-02-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
