# Generated by Django 4.0.1 on 2022-02-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_tarifforder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('videos', models.IntegerField(verbose_name='количество видео')),
                ('photos', models.IntegerField(verbose_name='количество фото')),
                ('adds', models.IntegerField(verbose_name='количесто автоподбросов')),
                ('days', models.IntegerField(verbose_name='Количество дней')),
            ],
            options={
                'verbose_name': 'Элемент покупки',
                'verbose_name_plural': 'Элементы покупки',
            },
        ),
        migrations.RemoveField(
            model_name='tarifforder',
            name='tarif_name',
        ),
    ]
