# Generated by Django 4.0.1 on 2022-02-12 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_tarifforderitem_remove_tarifforder_tarif_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifforderitem',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.tarifforder', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
