# Generated by Django 4.0.1 on 2022-02-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_tarifforderitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifforder',
            options={'ordering': ('-created',), 'verbose_name': 'Смена тарифа', 'verbose_name_plural': 'Смены тарифов'},
        ),
        migrations.AddField(
            model_name='tarifforderitem',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
