# Generated by Django 4.0.1 on 2022-02-12 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_remove_rate_adds_bonus_remove_rate_bonus_end_and_more'),
        ('orders', '0008_alter_tarifforder_options_tarifforderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifforderitem',
            name='name',
        ),
        migrations.AddField(
            model_name='tarifforderitem',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rates.rate', verbose_name='Тариф'),
        ),
    ]
